### ISSUE TITLE
Potential Initialisation bug?

### ISSUE THREAD

**Issue by sam-brett** [jonasmalacofilho/liquidctl#161]
Hello, 

I've just tried to run the initialise command on my Corsair H100i Platinum, which caused an error. Please see stack dump below. I'm aware this is an experimental feature, so I'm happy to provide more details if needed. 

```
sam@Sams-iMac liquidctl % liquidctl -m Corsair list                        
Device ID 0: Corsair H100i Platinum (experimental)
sam@Sams-iMac liquidctl % liquidctl -m Corsair -g initialize     
[DEBUG] liquidctl.cli: running liquidctl v1.3.3 (homebrew; liquidctl HEAD-f44281d)
[DEBUG] liquidctl.driver.usb: searching HidapiBus (api=hid, drivers=[CommonSmartDeviceDriver, CoolitPlatinumDriver, CorsairHidPsuDriver, KrakenTwoDriver, KrakenX3Driver, KrakenZ3Driver, RGBFusion2Driver, SeasonicEDriver, SmartDeviceDriver, SmartDeviceV2Driver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0221
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0221
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c18
[DEBUG] liquidctl.driver.usb: instanced driver for Corsair H100i Platinum (experimental)
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c1a
[DEBUG] liquidctl.driver.usb: probing drivers for device 048d:5702
[DEBUG] liquidctl.driver.usb: probing drivers for device 048d:5702
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (drivers=[AsetekDriver, CommonAsetekDriver, CorsairAsetekDriver, LegacyAsetekDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0221
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c1a
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c18
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:0265
[DEBUG] liquidctl.driver.usb: probing drivers for device 05ac:1006
[DEBUG] liquidctl.driver.usb: probing drivers for device 1235:8014
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.driver.usb: probing drivers for device 0bda:0411
[DEBUG] liquidctl.driver.usb: probing drivers for device 048d:5702
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0612
[DEBUG] liquidctl.driver.usb: probing drivers for device 0bda:5411
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0610
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.cli: device: Corsair H100i Platinum (experimental)
Traceback (most recent call last):
  File "/usr/local/bin/liquidctl", line 33, in <module>
    sys.exit(load_entry_point('liquidctl==1.3.3', 'console_scripts', 'liquidctl')())
  File "/usr/local/Cellar/liquidctl/HEAD-f44281d_1/libexec/lib/python3.8/site-packages/liquidctl/cli.py", line 298, in main
    dev.connect(**opts)
  File "/usr/local/Cellar/liquidctl/HEAD-f44281d_1/libexec/lib/python3.8/site-packages/liquidctl/driver/coolit_platinum.py", line 151, in connect
    self._data = RuntimeStorage(key_prefixes=[ids, self.address])
  File "/usr/local/Cellar/liquidctl/HEAD-f44281d_1/libexec/lib/python3.8/site-packages/liquidctl/keyval.py", line 107, in __init__
    self._backend = _FilesystemBackend(key_prefixes)
  File "/usr/local/Cellar/liquidctl/HEAD-f44281d_1/libexec/lib/python3.8/site-packages/liquidctl/keyval.py", line 63, in __init__
    os.makedirs(self._write_dir, exist_ok=True)
  File "/usr/local/Cellar/liquidctl/HEAD-f44281d_1/libexec/bin/../lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 63] File name too long: '/Library/Application Support/liquidctl/1b1c_0c18/SU9TZXJ2aWNlOi9BcHBsZUFDUElQbGF0Zm9ybUV4cGVydC9QQ0kwQDAvQXBwbGVBQ1BJUENJL1hIQ0AxNC9YSENAMTQwMDAwMDAvSFMxMUAxNGEwMDAwMC9VU0IyLjAgSHViQDE0YTAwMDAwL0FwcGxlVVNCMjBJbnRlcm5hbEh1YkAxNGEwMDAwMC9BcHBsZVVTQjIwSHViUG9ydEAxNGExMDAwMC9VU0IyLjAgSHViQDE0YTEwMDAwL0FwcGxlVVNCMjBIdWJAMTRhMTAwMDAvQXBwbGVVU0IyMEh1YlBvcnRAMTRhMTIwMDAvSDEwMGkgUGxhdGludW1AMTRhMTIwMDAvSU9VU0JIb3N0SW50ZXJmYWNlQDAvQXBwbGVVc2VyVVNCSG9zdEhJRERldmljZQ=='
```

**Comment by jonasmalacofilho** [comment]
@sam-brett,

This should be fixed in the latest HEAD (currently at 4028c26e1b05).  Can you give it a try and confirm that it fixes the issue?
