### ISSUE TITLE
Resource busy errors when simultaneously accessing 690LC devices

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/liquidctl#42]
Simultaneously running

```
# extra/liquiddump --product 0xb200 --interval 3
# extra/tests/asetek_modern
```

in different shells causes the second to exit (first) with `Resource busy`.

Next, the other one fails as well with `Operation timed out`.  That happens even if `--interval` is set to a high value and everything else clearly happens when it's `time.sleep`-ing.

```
# extra/liquiddump --product 0xb200 --interval 3
{"Asetek 690LC (assuming EVGA CLC)": [["Liquid temperature", 28.8, "\u00b0C"], ["Fan speed", 420, "rpm"], ["Pump speed", 2670, "rpm"], ["Firmware version", "2.10.0.0", ""]]}
{"Asetek 690LC (assuming EVGA CLC)": [["Liquid temperature", 28.8, "\u00b0C"], ["Fan speed", 480, "rpm"], ["Pump speed", 2610, "rpm"], ["Firmware version", "2.10.0.0", ""]]}
{"Asetek 690LC (assuming EVGA CLC)": [["Liquid temperature", 28.8, "\u00b0C"], ["Fan speed", 420, "rpm"], ["Pump speed", 2640, "rpm"], ["Firmware version", "2.10.0.0", ""]]}
Unexpected error
Traceback (most recent call last):
  File "extra/liquiddump", line 92, in <module>
    status[d.description] = d.get_status()
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/asetek.py", line 221, in get_status
    msg = self._end_transaction_and_read()
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/asetek.py", line 140, in _end_transaction_and_read
    msg = self.device.read(_READ_ENDPOINT, _READ_LENGTH, _READ_TIMEOUT)
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/usb.py", line 260, in read
    return self.usbdev.read(endpoint, length, timeout=timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

$ echo $?
0
```

and on shell B:

```
# extra/tests/asetek_modern
+ DEVICE='--vendor 0x2433 --product 0xb200'
+ liquidctl --vendor 0x2433 --product 0xb200 list --verbose
Device 0, Asetek 690LC (assuming EVGA CLC)
  Vendor ID: 0x2433
  Product ID: 0xb200
  Release number: 0x0100
  Serial number: CCVI_1.0
  Bus: usb1
  Address: 10
  Port: 12
  Hierarchy: AsetekDriver, CommonAsetekDriver, UsbDeviceDriver, BaseDriver; PyUsbDevice=usb

+ liquidctl --vendor 0x2433 --product 0xb200 initialize
+ sleep 2
+ liquidctl --vendor 0x2433 --product 0xb200 status
Device 0, Asetek 690LC (assuming EVGA CLC)
usb.core.USBError: [Errno 16] Resource busy

$ echo $?
1
```

~~Additional issue: shell A exists with code 0~~ (fixed in a0a983409b9321bb874d892d5c22514eb33a0639)
Reported by: @source83

**Comment by jonasmalacofilho** [comment]
A traceback from shell B:

```
#EXTRAOPTIONS=-g extra/tests/asetek_modern
...
+ liquidctl --vendor 0x2433 --product 0xb200 -g set fan speed 0
[DEBUG] liquidctl.driver.asetek: open device
[INFO] liquidctl.driver.asetek: using a flat profile to set fan to a fixed duty
[INFO] liquidctl.driver.asetek: filling missing 4 PWM points with (60°C, 100%)
[INFO] liquidctl.driver.asetek: setting fan PWM point: (0°C, 0%), device interpolated
[INFO] liquidctl.driver.asetek: setting fan PWM point: (59°C, 0%), device interpolated
[INFO] liquidctl.driver.asetek: setting fan PWM point: (60°C, 100%), device interpolated
[INFO] liquidctl.driver.asetek: setting fan PWM point: (60°C, 100%), device interpolated
[INFO] liquidctl.driver.asetek: setting fan PWM point: (60°C, 100%), device interpolated
[INFO] liquidctl.driver.asetek: setting fan PWM point: (60°C, 100%), device interpolated
[DEBUG] liquidctl.driver.asetek: begin transaction
[DEBUG] liquidctl.driver.asetek: write 11 00 00 3b 3c 3c 3c 3c 00 00 64 64 64 64
[ERROR] liquidctl.cli: Unexpected error
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/liquidctl/cli.py", line 233, in main
    _device_set_speed(dev, args, **frwd)
  File "/usr/lib/python3.7/site-packages/liquidctl/cli.py", line 188, in _device_set_speed
    dev.set_fixed_speed(args['<channel>'], int(args['<percentage>'][0]), **kwargs)
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/asetek.py", line 296, in set_fixed_speed
    self.set_speed_profile(channel, [(0, duty), (_CRITICAL_TEMPERATURE - 1, duty)])
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/asetek.py", line 283, in set_speed_profile
    self._write([mtype, 0] + temps + duties)
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/asetek.py", line 129, in _write
    self.device.write(_WRITE_ENDPOINT, data, _WRITE_TIMEOUT)
  File "/usr/lib/python3.7/site-packages/liquidctl/driver/usb.py", line 264, in write
    return self.usbdev.write(endpoint, data, timeout=timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
[DEBUG] liquidctl.driver.asetek: close device
```

Technically this was during another run and the failure happened a little later in the test script, but it's the same issue (and the stack trace is the same up to `self._write`).

**Comment by jonasmalacofilho** [comment]
The behavior after 1883ca4197b0a9fac21f4359cb3a485570dfbc3f ("Rework USBXPRESS flow control to allow simultaneous access") and 3c7596ea069ff45d3cf8f07ffe7dbb89a04f1e29 ("Claim the interface proactively when starting a 690LC transaction") should now be a lot more reasonable.

Of course, when two programs are racing to claim the same device (interface), it's entirely reasonable that sometimes one of them will get a "Resource busy" error.  But, after these changes, the device holding the interface at the time of the race should be able to proceed normally.

"Resource busy" errors should also be far less common now, as before running a single program at a time, if in quick enough succession, could cause problems.

Still, busy errors are to be excepted when there are races, and there's probably no easy way to handle that outside of the kernel.  Programs/scripts excepted to handle such races should then also be made to deal with such errors.

---

Leaving the issue open for a little while because liquiddump is one these scripts that needs a fix.

**Comment by jonasmalacofilho** [comment]
Closing with 9e8b0f1c837707cdebfc064300a8b9afb0349f0e ("Make liquiddump tolerant to USB failures during any get_status").

@source83 let me know if busy errors are still common for you.
