### ISSUE TITLE
Characters used for the list/status "trees" are invalid with LC_ALL=C

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/liquidctl#84]
_Waiting for additional info (can't reproduce yet)._

Reported-by: Jack Zhang ([Twitter](https://twitter.com/Jack_Y_Zhang/status/1226636682033684480?s=20))

**Comment by jonasmalacofilho** [comment]
Additional info:

 - reportedly only happens with `LC_ALL=C` in `/etc/environment` (but I still can't reproduce it)
 - calling liquidctl from a root shell (`sudo -s`) in Konsole

**Comment by jonasmalacofilho** [comment]
```
[DEBUG] liquidctl.cli: running liquidctl v1.3.2
[DEBUG] liquidctl.driver.usb: searching GenericHidBus (api=hidraw, drivers=[CommonSmartDeviceDriver, CorsairHidPsuDriver, KrakenTwoDriver, SeasonicEDriver, SmartDeviceDriver, SmartDeviceV2Driver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x46d:0xc07d
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x46d:0xc07d
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0x1b15
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (drivers=[AsetekDriver, CommonAsetekDriver, CorsairAsetekDriver, LegacyAsetekDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x2433:0xb200
[DEBUG] liquidctl.driver.usb: instanced driver for Asetek 690LC (assuming EVGA CLC)
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x8087:0x24
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0x1b15
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x46d:0xc07d
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x8087:0x24
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.cli: device: Asetek 690LC (assuming EVGA CLC)
[DEBUG] liquidctl.driver.asetek: set clear to send = True
[DEBUG] liquidctl.driver.asetek: begin transaction
[DEBUG] liquidctl.driver.usb: explicitly claim interface
[DEBUG] liquidctl.driver.asetek: write 14 00 00 00
[DEBUG] liquidctl.driver.asetek: received 00 00 01 49 00 06 01 10 0a aa 1b 14 00 00 02 f8 00 22 ff 09 00 ff 00 02 0a 00 00 ff ff a9 51 3e
[DEBUG] liquidctl.driver.usb: ensure interface is released
Asetek 690LC (assuming EVGA CLC)
[ERROR] liquidctl.cli: Unexpected error with Asetek 690LC (assuming EVGA CLC)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/cli.py", line 309, in main
    _print_dev_status(dev, dev.get_status(**opts))
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/cli.py", line 208, in _print_dev_status
    print(f'\u251c\u2500\u2500 {k:<{kcols}}    {v:>{vcols}}  {u}')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
[DEBUG] liquidctl.driver.usb: ensure interface is released
```

> _Konsole 17.12.3, Python 3.6, Ubuntu 18.04.4 LTS, Kernel 5.0.0-37-generic, /bin/bash is the shell._
_–Jack Zhang ([Twitter](https://twitter.com/Jack_Y_Zhang/status/1227840351529918464))_

---

Setting `LC_ALL=C` [breaks Python 3.6](https://bugs.python.org/issue19846) by the default.  Or, more accurately, it makes Python 3.6 behave very strictly (in a Unicode world), which is not what users using the `LC_ALL=C` sledgehammer expect.

Python 3.7 relaxes this a lot with the implementation of [PEP 538](https://www.python.org/dev/peps/pep-0538/) and its successors, because it acknowledges that every time a `C` locale is found it isn't because of a real limitation of the OS.  So the exception is gone in Python 3.7 (at least in most real world cases).

The use of Unicode in liquidctl isn't limited to box drawing characters: there are two other places, one of them being the degrees Celsius `°C` unit.  And while that may still look superficial to some, I don't agree: I think that using these bits of Unicode significantly improve the legibility of the CLI.

So here are a few workarounds for Python 3.6:

 - use `PYTHONIOENCODING=:replace` or `PYTHONIOENCODING=:backslashreplace` to make Python 3.6 less strict and avoid the exception¹
 - run liquidctl with a different/Unicode locale, again avoiding the exception; for example: `LC_ALL=en_US.utf8 liquidctl status`

Also a few recommendations (if I may):

 - try to be more specific when using the `C` locale to fix _something;_ use `LC_*` variables other than `LC_ALL`, _if possible_
 - try not to set `LC_ALL=C` indiscriminately/to all programs, _if possible_

Finally, I'm still considering how to improve the appearance of the CLI output in terminal shells started with `LC_ALL=C`, where the current use of Unicode produces garbage (Python 3.7+ or Python 3.6 using the workarounds above).

_¹ You may also specify the encoding: `PYTHONIOENCODING=ascii:replace` or `PYTHONIOENCODING=ascii:backslashreplace`._

**Comment by jonasmalacofilho** [comment]
Closing this with 'wont fix' (for now):

 - the exception in Python 3.6 can be worked around (see previous comment)
 - fixing the rendering on the C locale can be done cleanly, but only for Python >= 3.7
 - removing the use of any non-ASCII characters would make the CLI uglier, and possibly even break some user scripts¹
 - indiscriminately using `LC_ALL=C` is expected to cause some issues

¹ While this it's not very likely to be used in practice, it would break matches for `°C`.

**Comment by jonasmalacofilho** [comment]
Additional notes:

 - This happens because Python 3.6 doesn't try to coerce ASCII locales to UTF-8;
 - but only `stdout` is affected, as for `stderr` the error handler is always `backslashreplace`.

**Comment by jonasmalacofilho** [comment]
This is a bug alright, though I'm considering it to have low priority; indiscriminately using `LC_ALL=C` is expected to cause some issues.[[1]](https://wiki.archlinux.org/index.php/locale#LC_ALL:_troubleshooting)[[2]](https://wiki.debian.org/Locale)
